#!/usr/bin/env python3
# Copyright (c) 2026 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Validate iOS OCR pipeline output against PaddleX reference output.

Compares per-image JSON files produced by the iOS demo against reference
JSON files generated by generate_reference.py.  Reports exact match or
detailed differences for each image.

Match criteria:
    - Polygon coordinates: exact integer match
    - Recognized text: exact string match
    - Confidence scores: within tolerance of 1e-4 (ARM vs x86 float diff)
    - Box count: exact match
    - Box order: compared in array order (both in reading order)

Usage:
    python3 validate.py [--ios-dir DIR] [--reference-dir DIR] [--verbose]

Exit codes:
    0 = all images match
    1 = at least one mismatch found
    2 = missing files or other error
"""

import argparse
import json
import sys
from pathlib import Path


CONFIDENCE_TOLERANCE = 1e-4


def compare_polygons(ios_poly: list, ref_poly: list) -> list:
    """Compare two polygons (lists of [x, y] integer pairs).

    Returns:
        List of human-readable difference strings.  Empty if polygons match.
    """
    diffs = []
    if len(ios_poly) != len(ref_poly):
        diffs.append(f"Point count: iOS={len(ios_poly)} ref={len(ref_poly)}")
        return diffs
    for i, (ios_pt, ref_pt) in enumerate(zip(ios_poly, ref_poly)):
        if ios_pt[0] != ref_pt[0] or ios_pt[1] != ref_pt[1]:
            diffs.append(f"Point {i}: iOS={ios_pt} ref={ref_pt}")
    return diffs


def compare_boxes(ios_box: dict, ref_box: dict, index: int) -> list:
    """Compare a single box pair across polygon, text, and confidence.

    Returns:
        List of human-readable issue strings.  Empty if the box matches.
    """
    issues = []

    # Polygon comparison (exact integer match)
    poly_diffs = compare_polygons(ios_box["polygon"], ref_box["polygon"])
    if poly_diffs:
        issues.append(f"  Box {index} polygon: {'; '.join(poly_diffs)}")

    # Text comparison (exact string match)
    if ios_box["text"] != ref_box["text"]:
        issues.append(
            f"  Box {index} text: iOS='{ios_box['text']}' ref='{ref_box['text']}'"
        )

    # Confidence comparison (within tolerance)
    ios_conf = ios_box["confidence"]
    ref_conf = ref_box["confidence"]
    if abs(ios_conf - ref_conf) > CONFIDENCE_TOLERANCE:
        issues.append(
            f"  Box {index} confidence: iOS={ios_conf:.6f} ref={ref_conf:.6f} "
            f"(diff={abs(ios_conf - ref_conf):.6f}, tolerance={CONFIDENCE_TOLERANCE})"
        )

    return issues


def validate(ios_dir: str, reference_dir: str, verbose: bool = False) -> bool:
    """Compare iOS output against reference.

    Args:
        ios_dir: Path to directory containing iOS-exported JSON files.
        reference_dir: Path to directory containing reference JSON files.
        verbose: If True, also print PASS results.

    Returns:
        True if all images match, False otherwise.
    """
    ios_path = Path(ios_dir)
    ref_path = Path(reference_dir)

    if not ref_path.exists():
        print(
            f"Error: Reference directory not found: {reference_dir}",
            file=sys.stderr,
        )
        print("Run generate_reference.py first.", file=sys.stderr)
        sys.exit(2)

    if not ios_path.exists():
        print(
            f"Error: iOS output directory not found: {ios_dir}",
            file=sys.stderr,
        )
        print("Export iOS pipeline results as JSON first.", file=sys.stderr)
        sys.exit(2)

    ref_files = sorted(ref_path.glob("*.json"))
    if not ref_files:
        print(
            f"Error: No reference JSON files in {reference_dir}",
            file=sys.stderr,
        )
        sys.exit(2)

    all_pass = True
    total_images = 0
    total_boxes = 0
    matched_boxes = 0

    for ref_file in ref_files:
        ios_file = ios_path / ref_file.name
        if not ios_file.exists():
            print(f"MISSING: {ref_file.name} -- no iOS output found")
            all_pass = False
            continue

        with open(ref_file, "r", encoding="utf-8") as f:
            ref_data = json.load(f)
        with open(ios_file, "r", encoding="utf-8") as f:
            ios_data = json.load(f)

        total_images += 1
        image_name = ref_data["image"]
        ref_boxes = ref_data["boxes"]
        ios_boxes = ios_data["boxes"]

        if len(ios_boxes) != len(ref_boxes):
            print(
                f"FAIL: {image_name} -- box count: "
                f"iOS={len(ios_boxes)} ref={len(ref_boxes)}"
            )
            all_pass = False
            continue

        image_issues = []
        for i, (ios_box, ref_box) in enumerate(zip(ios_boxes, ref_boxes)):
            total_boxes += 1
            box_issues = compare_boxes(ios_box, ref_box, i)
            if box_issues:
                image_issues.extend(box_issues)
            else:
                matched_boxes += 1

        if image_issues:
            print(f"FAIL: {image_name}")
            for issue in image_issues:
                print(issue)
            all_pass = False
        elif verbose:
            print(f"PASS: {image_name} ({len(ref_boxes)} boxes)")

    # Summary
    print(f"\n{'=' * 50}")
    print(f"Images: {total_images}")
    print(f"Boxes:  {matched_boxes}/{total_boxes} matched")
    print(f"Result: {'ALL PASS' if all_pass else 'FAIL'}")
    print(f"{'=' * 50}")

    return all_pass


def main():
    parser = argparse.ArgumentParser(
        description="Validate iOS OCR output against PaddleX reference"
    )
    parser.add_argument(
        "--ios-dir",
        default="deploy/ios_demo/Validation/ios_output",
        help=(
            "Directory containing iOS output JSON "
            "(default: deploy/ios_demo/Validation/ios_output)"
        ),
    )
    parser.add_argument(
        "--reference-dir",
        default="deploy/ios_demo/Validation/reference",
        help=(
            "Directory containing reference JSON "
            "(default: deploy/ios_demo/Validation/reference)"
        ),
    )
    parser.add_argument(
        "--verbose",
        "-v",
        action="store_true",
        help="Print PASS results too",
    )
    args = parser.parse_args()

    success = validate(args.ios_dir, args.reference_dir, args.verbose)
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
