Global:
  use_gpu: true
  epoch_num: 100
  log_smooth_window: 20
  print_batch_step: 20
  save_model_dir: ./output/lr_o1_matmul_add
  save_epoch_step: 1
  eval_batch_step:
  - 0
  - 2000
  cal_metric_during_train: true
  pretrained_model: null
  checkpoints: ./output/check/old_no_lr/amp11_mul_add_right/best_accuracy
  save_inference_dir: null
  use_visualdl: false
  infer_img: ppstructure/docs/table/table.jpg
  save_res_path: output/rerun_table_mv3
  character_dict_path: ppocr/utils/dict/table_structure_dict.txt
  character_type: en
  max_text_length: 500
  box_format: xyxy
  infer_mode: false
  use_amp: true
  amp_level: O1
  amp_custom_black_list:
  - matmul_v2
  - elementwise_add
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  clip_norm: 5.0
  lr:
    learning_rate: 0.0001
  regularizer:
    name: L2
    factor: 0.0
Architecture:
  model_type: table
  algorithm: TableAttn
  Backbone:
    name: MobileNetV3
    scale: 1.0
    model_name: small
    disable_se: true
  Head:
    name: TableAttentionHead
    hidden_size: 256
    loc_type: 2
    max_text_length: 500
    loc_reg_num: 4
Loss:
  name: TableAttentionLoss
  structure_weight: 100.0
  loc_weight: 10000.0
PostProcess:
  name: TableLabelDecode
Metric:
  name: TableMetric
  main_indicator: acc
  compute_bbox_metric: false
Train:
  dataset:
    name: PubTabDataSet
    data_dir: ../pubtabnet/train/
    label_file_list:
    - ../pubtabnet/PubTabNet_2.0.0_train.jsonl
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - TableLabelEncode:
        learn_empty_box: false
        merge_no_span_structure: false
        replace_empty_cell_token: false
        loc_reg_num: 4
        max_text_length: 500
    - TableBoxEncode: null
    - ResizeTableImage:
        max_len: 488
    - NormalizeImage:
        scale: 1./255.
        mean:
        - 0.485
        - 0.456
        - 0.406
        std:
        - 0.229
        - 0.224
        - 0.225
        order: hwc
    - PaddingTableImage:
        size:
        - 488
        - 488
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - structure
        - bboxes
        - bbox_masks
        - shape
  loader:
    shuffle: true
    batch_size_per_card: 40
    drop_last: true
    num_workers: 1
Eval:
  dataset:
    name: PubTabDataSet
    data_dir: ../pubtabnet/val/
    label_file_list:
    - ../pubtabnet/PubTabNet_2.0.0_val.jsonl
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - TableLabelEncode:
        learn_empty_box: false
        merge_no_span_structure: false
        replace_empty_cell_token: false
        loc_reg_num: 4
        max_text_length: 500
    - TableBoxEncode: null
    - ResizeTableImage:
        max_len: 488
    - NormalizeImage:
        scale: 1./255.
        mean:
        - 0.485
        - 0.456
        - 0.406
        std:
        - 0.229
        - 0.224
        - 0.225
        order: hwc
    - PaddingTableImage:
        size:
        - 488
        - 488
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - structure
        - bboxes
        - bbox_masks
        - shape
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 40
    num_workers: 1
profiler_options: null
