Global:
  use_gpu: true
  epoch_num: 600
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/det_ct/
  save_epoch_step: 10
  # evaluation is run every 2000 iterations
  eval_batch_step: [0,2000]
  cal_metric_during_train: False
  pretrained_model: ../PaddleOCR.bck1/pretrain_models/ResNet18_pretrained.pdparams #./pretrain_models/ResNet50_vd_ssld_pretrained
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img: doc/imgs_en/img_10.jpg
  save_res_path: ./output/det_db/predicts_db.txt

Architecture:
  model_type: det
  algorithm: CT
  Transform:
  Backbone:
    name: ResNet
    layers: 18
  Neck:
    name: CTNECK
  Head:
    name: CT_Head
    in_channels: 512
    hidden_dim: 128
    num_classes: 3

Loss:
  name: CTLoss

Optimizer:
  name: Adam
  lr:
    name: Linear #PolynomialDecay
    learning_rate: 0.001 #1e-3
    end_lr: 0.
    epochs: 600
    step_each_epoch: 1254
    #decay_steps: 752400 #max_iter_num
    power: 0.9

PostProcess:
  name: CTPostProcess

Metric:
  name: CTMetric
  gt_dir: '/workspace/huangjun12/PaddleProject/OCR/CentripetalText/0.WellTrained/data/total_text/Groundtruth/Polygon/Test/'
  main_indicator: f_score #Hmean

Train:
  dataset:
    name: SimpleDataSet
    # data_dir: /workspace/huangjun12/PaddleProject/OCR/CentripetalText/0.WellTrained/data/total_text/Images/Train/
    # label_file_list:
    #   - /workspace/huangjun12/PaddleProject/OCR/CentripetalText/0.WellTrained/data/total_text/Groundtruth/Polygon/Train
    # data_dir: data/total_text/train/
    # label_file_list:
    #   - data/total_text/train/train.txt
    data_dir: /workspace/huangjun12/PaddleProject/OCR/CentripetalText/0.WellTrained/data/total_text/Images/
    label_file_list:
      - ./Train.list
    ratio_list: [1.0]
    transforms:
      - DecodeImage:
          img_mode: RGB
          channel_first: False
      - CTLabelEncode: # Class handling label
      - RandomScale:
      - MakeShrink:
      - RandomHorizontalFlip:
      - RandomRotate:
      - RandomCropPadding:
      - GetCentripetalShift:
      - ColorJitterNormalize: 
      - KeepKeys:
          keep_keys: ['image', 'gt_kernel', 'training_mask', 'gt_instance', 'gt_kernel_instance', 'training_mask_distance', 'gt_distance'] # the order of the dataloader list
  loader:
    shuffle: True
    drop_last: True
    batch_size_per_card: 4
    num_workers: 8 #4

Eval:
  dataset:
    name: SimpleDataSet
    # data_dir: /workspace/huangjun12/PaddleProject/OCR/CentripetalText/0.WellTrained/data/total_text/Images/Train/
    # label_file_list:
    #   - /workspace/huangjun12/PaddleProject/OCR/CentripetalText/0.WellTrained/data/total_text/Groundtruth/Polygon/Train
    # data_dir: data/total_text/test/
    # label_file_list:
    #   - data/total_text/test/test.txt
    data_dir: /workspace/huangjun12/PaddleProject/OCR/CentripetalText/0.WellTrained/data/total_text/Images/
    label_file_list:
      - ./Test.list
    ratio_list: [1.0]
    transforms:
      - DecodeImage:
          img_mode: RGB
          channel_first: False
      - ScaleAlignedShort:
      - ColorJitterNormalize:
          cj: False
      - KeepKeys:
          keep_keys: ['image', 'org_img_size', 'img_size', 'img_path'] # the order of the dataloader list          
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 1
    num_workers: 2
