Global:
  use_gpu: true
  epoch_num: 600
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/det_ct/
  save_epoch_step: 10
  # evaluation is run every 2000 iterations
  eval_batch_step: [0,1000]
  cal_metric_during_train: False
  pretrained_model: ./pretrain_models/ResNet18_vd_pretrained.pdparams
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img: doc/imgs_en/img623.jpg
  save_res_path: ./output/det_ct/predicts_ct.txt

Architecture:
  model_type: det
  algorithm: TPM
  Transform:
  Backbone:
    name: ResNet
    layers: 50
  Neck:
    name: TPMFPN
  Head:
    name: TPMRRGN
    in_channels: 1024
    f_num: 4 # default

Loss:
  name: CTLoss

Optimizer:
  name: Adam
  lr:  #PolynomialDecay
    name: Linear 
    learning_rate: 0.001
    end_lr: 0.
    epochs: 600
    step_each_epoch: 1254
    power: 0.9

PostProcess:
  name: TPMPostProcess
  box_type: poly  # not support quad now

Metric:
  name: DetMetric
  main_indicator: hmean

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/total_text/train
    label_file_list:
      - ./train_data/total_text/train/train.txt
    ratio_list: [1.0]
    transforms:
      - DecodeImage: # load image
          img_mode: RGB
          channel_first: False
      - DetLabelEncode: # Class handling label
      - IaaAugment:
          augmenter_args:
            - { 'type': Fliplr, 'args': { 'p': 0.5 } }
            - { 'type': Affine, 'args': { 'rotate': [-10, 10] } }
            - { 'type': Resize, 'args': { 'size': [0.5, 3] } }
      - EastRandomCropData:
          size: [640, 640]
          max_tries: 50
          keep_ratio: true
      - MakeShrinkMap:
          shrink_ratio: 0.6
          min_text_size: 8
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'shrink_map', 'shrink_mask'] 
  loader:
    shuffle: True
    drop_last: True
    batch_size_per_card: 4
    num_workers: 8

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/total_text/test
    label_file_list:
      - ./train_data/total_text/test/test.txt
    ratio_list: [1.0]
    transforms:
      - DecodeImage: # load image
          img_mode: RGB
          channel_first: False
      - DetLabelEncode: # Class handling label
      - ScaleAlignedShort:
      - NormalizeImage:
          order: 'hwc'
      - ToCHWImage: 
      - KeepKeys:
          keep_keys: ['image', 'shape', 'polys', 'texts'] # the order of the dataloader list          
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 1
    num_workers: 2
