DATA:
  DICT: PageNet/PageNet_pytorch/dicts/casia-hwdb.txt
  VAL:
    DATA_ROOT: IC13Comp
    WIDTHS:
      - 1920
    MAX_HEIGHT: 2080 
    SIZE_STRIDE: 16
    BATCH_SIZE: 1
    IMAGE_MODE: 'np.tobytes'
  NUM_WORKER: 3
MODEL:
  WEIGHTS: 'PageNet/PageNet_pytorch/outputs/casia-hwdb/checkpoints/casia-hwdb.pth'
  BACKBONE:
    BLOCK: basicblock
    IN_CHANNEL: 1
    LAYERS: 
      - 2
      - 2
      - 2
      - 2
    CHANNELS:
      - 64
      - 128
      - 256
      - 512
  FEAT:
    BOX_CHANNELS:
      - 256
      - 128
      - 64
    DIS_CHANNELS:
      - 256
      - 128
      - 64
    CLS_CHANNELS:
      - 512 
      - 512 
      - 1024
    ROM_CHANNELS:
      - 64
      - 64
  PRED:
    DROPOUT: 0.5
    NUM_CLASSES: 7356
POST_PROCESS:
  DIS_WEIGHT: 0.8
  CONF_THRES: 0.8
  NMS_THRES: 0.15
  SOL_EOL_CONF_THRES: 0.9
  READ_ORDER_MAX_STEP: 20
#OUTPUT_FOLDER: './outputs/casia-hwdb'
OUTPUT_FOLDER: 'PageNet/PageNet_pytorch/outputs/casia-hwdb'

