# PaddleOCR

name: ðŸ› Bug Report

# title: " "

description: Problems with PaddleOCR
labels: [bug, triage]
body:

- type: markdown
    attributes:
      value: |
        Thank you for submitting a PaddleOCR ðŸ› Bug Report!

- type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/), [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) to see if a similar bug report already exists.
      options:
        - label: >
            I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
          required: true
        - label: >
            I have searched the PaddleOCR [Issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.
          required: true
        - label: >
            I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.
          required: true

- type: textarea
    attributes:
      label: Bug
      description: Provide console output with error messages and/or screenshots of the bug.
      placeholder: |
        ðŸ’¡ ProTip! Include as much information as possible (screenshots, logs, tracebacks etc.) to receive the most helpful response.
    validations:
      required: true

- type: textarea
    attributes:
      label: Environment
      description: Please specify the software and hardware you used to produce the bug.
      placeholder: |
        Paste output of `yolo checks` or `ultralytics.checks()` command, i.e.:
        ```
        OS                  macOS-13.5.2
        Environment         Jupyter
        Python              3.11.2
        PaddleOCR           2.8.1
        Install             git
        RAM                 16.00 GB
        CPU                 Apple M2
        CUDA                None
        ```
    validations:
      required: false

- type: textarea
    attributes:
      label: Minimal Reproducible Example
      description: >
        When asking a question, people will be better able to provide help if you provide code that they can easily understand and use to **reproduce** the problem.
        This is referred to by community members as creating a [minimal reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/).
      placeholder: |
        ```
        # Code to reproduce your issue here
        ```
    validations:
      required: false

- type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?

- type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        (Optional) We encourage you to submit a [Pull Request](https://github.com/PaddlePaddle/PaddleOCR/pulls) (PR) to help improve PaddleOCR for everyone, especially if you have a good understanding of how to implement a fix or feature.
        See the PaddleOCR [community_contribution](https://paddlepaddle.github.io/PaddleOCR/community/community_contribution.html#2) to get started.
      options:
        - label: Yes I'd like to help by submitting a PR!
