mean:
  -
    - 123.675
    - 116.28
    - 103.53
std:
  -
    - 58.395
    - 57.12
    - 57.375
model_path: ./PP-OCRv3_mobile_det_infer/PP-OCRv3_mobile_det_infer.onnx
outputs_nodes:
do_quantization: False
dataset:
output_folder: "./PP-OCRv3_mobile_det_infer"
