Global:
  debug: false
  use_gpu: true
  epoch_num: 200
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec_dkd_400w_svtr_ctc_lcnet_blank_dkd0.1/
  save_epoch_step: 40
  eval_batch_step:
  - 0
  - 2000
  cal_metric_during_train: true
  pretrained_model: null
  checkpoints: ./output/rec_dkd_400w_svtr_ctc_lcnet_blank_dkd0.1/latest
  save_inference_dir: null
  use_visualdl: false
  infer_img: doc/imgs_words/ch/word_1.jpg
  character_dict_path: ppocr/utils/ppocr_keys_v1.txt
  max_text_length: 25
  infer_mode: false
  use_space_char: true
  distributed: true
  save_res_path: ./output/rec/predicts_ppocrv3.txt
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 2
  regularizer:
    name: L2
    factor: 3.0e-05
Architecture:
  model_type: rec
  name: DistillationModel
  algorithm: Distillation
  Models:
    Teacher:
      pretrained: 
      freeze_params: true
      return_all_feats: true
      model_type: rec
      algorithm: SVTR
      Transform: null
      Backbone:
        name: SVTRNet
        img_size:
        - 48
        - 320
        out_char_num: 40
        out_channels: 192
        patch_merging: Conv
        embed_dim:
        - 64
        - 128
        - 256
        depth:
        - 3
        - 6
        - 3
        num_heads:
        - 2
        - 4
        - 8
        mixer:
        - Conv
        - Conv
        - Conv
        - Conv
        - Conv
        - Conv
        - Global
        - Global
        - Global
        - Global
        - Global
        - Global
        local_mixer:
        - - 5
          - 5
        - - 5
          - 5
        - - 5
          - 5
        last_stage: false
        prenorm: true
      Head:
        name: MultiHead
        head_list:
          - CTCHead:
              Neck:
                name: svtr
                dims: 120
                depth: 2
                hidden_dims: 120
                kernel_size: [1, 3]
                use_guide: True
              Head:
                fc_decay: 0.00001
          - NRTRHead:
              nrtr_dim: 384
              max_text_length: *max_text_length
    Student:
      pretrained: 
      freeze_params: false
      return_all_feats: true
      model_type: rec
      algorithm: SVTR
      Transform: null
      Backbone:
        name: PPLCNetV3
        scale: 0.95
      Head:
        name: MultiHead
        head_list:
          - CTCHead:
              Neck:
                name: svtr
                dims: 120
                depth: 2
                hidden_dims: 120
                kernel_size: [1, 3]
                use_guide: True
              Head:
                fc_decay: 0.00001
          - NRTRHead:
              nrtr_dim: 384
              max_text_length: *max_text_length
Loss:
  name: CombinedLoss
  loss_config_list:
  - DistillationDKDLoss:
      weight: 0.1
      model_name_pairs:
      - - Student
        - Teacher
      key: head_out
      multi_head: true
      alpha: 1.0
      beta: 2.0
      dis_head: gtc
      name: dkd
  - DistillationCTCLoss:
      weight: 1.0
      model_name_list:
      - Student
      key: head_out
      multi_head: true
  - DistillationNRTRLoss:
      weight: 1.0
      smoothing: false
      model_name_list:
      - Student
      key: head_out
      multi_head: true
  - DistillCTCLogits:
      weight: 1.0
      reduction: mean
      model_name_pairs:
      - - Student
        - Teacher
      key: head_out
PostProcess:
  name: DistillationCTCLabelDecode
  model_name:
  - Student
  key: head_out
  multi_head: true
Metric:
  name: DistillationMetric
  base_metric_name: RecMetric
  main_indicator: acc
  key: Student
  ignore_space: false
Train:
  dataset:
    name: SimpleDataSet
    data_dir: 400w_data/
    label_file_list:
    - 400w_data/real_data_disturb_v2.txt
    - 400w_data/ccpd_disturb_v2/rec_ccpd2019_disturb_fix_new_26w_scor90.txt
    - 400w_data/CCPD2019_rec/rec_all_fix_new_26w_scor90.txt
    - 400w_data/ctw_imgs/rec_ctw_train_val_file_list_new_26w_scor90.txt
    - 400w_data/InvoiceDatasets/rec_train_val_list_new_26w_scor90.txt
    - 400w_data/born_digit_disturb_v2/rec_born_digit_disturb_new_26w_scor90.txt
    - 400w_data/pubtabnet_crop_20_95_exa_20w.txt
    - 400w_data/lsvt_weak_imgs/unlabeled_train_list_82.4_shuaku_score_0.95_new26w.txt
    - 400w_data/rec_caibao_fileter_eng-score_0.95_new26w.txt
    - 400w_data/openimages_text_en/oidv5_label_new_new_26w_scor90_exa.txt
    - 400w_data/hard_vertical_img/hard_vertical_img_list_new_26w_scor90.txt
    - 400w_data/space_img_new/ch_label_0_new_26w_scor90.txt
    - 400w_data/seldom_new_26w_scor90_150w.txt
    - 400w_data/en_movies_img/en_movies_new_26w_scor90.txt
    - 400w_data/hospital_img/hospital_new_26w_scor90.txt
    - 400w_data/card_number_img/card_number_new_26w_scor90.txt
    - 400w_data/digital_img/digital_label_new_26w_scor90.txt
    - 400w_data/kie_img/kie_new_26w_scor90_exa.txt
    - 400w_data/layout_crop_label.txt
    - 400w_data/26w_RectsRects_label.txt
    - 400w_data/handwriting_label.txt
    - 400w_data/rec_ocr_tusou_v4/label_tusou_v4_0.95_1_list_chinese.txt
    - 400w_data/zhongce_rec_tusou_v1_20200901/rec_tusou_v4_zhongce_v1_20201130.txt
    ratio_list:
    - 1.0
    - 0.5
    - 0.25
    - 0.2
    - 1.0
    - 1.0
    - 0.2
    - 0.3
    - 0.4
    - 0.1
    - 0.2
    - 1.0
    - 0.025
    - 0.2
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 0.5
    - 0.43
    - 0.8
    - 0.06
    - 0.3
    ext_data_ratio_list:
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    - 0.0
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecAug: null
    - MultiLabelEncode:
        gtc_encode: NRTRLabelEncode
    - RecResizeImg:
        image_shape:
        - 3
        - 48
        - 320
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_gtc
        - length
        - valid_ratio
  loader:
    shuffle: true
    batch_size_per_card: 128
    drop_last: true
    num_workers: 8
    use_shared_memory: true
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ../
    label_file_list:
    - ../e2e_v4_4/label.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - MultiLabelEncode:
        max_text_length: 600
        character_dict_path: ppocr/utils/ppocr_keys_v1.txt
        use_space_char: true
    - RecResizeImg:
        image_shape:
        - 3
        - 48
        - 320
        eval_mode: true
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_gtc
        - length
        - valid_ratio
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 1
    num_workers: 16
profiler_options: null
