name: Lock

on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
  inactivity-lock:
    name: Lock issues and PRs
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: 🔒 Lock closed issues and PRs
        uses: klaasnicolaas/action-inactivity-lock@v1
        id: lock
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          rate-limit-buffer: 200
          days-inactive-issues: 30
          days-inactive-prs: -1
          lock-reason-issues: "This issue was locked because it has been inactive for 30 days since being closed."
          lock-reason-prs: "This PR was locked because it has been inactive for 30 days since being closed."
      - name: 🔍 Display locked issues and PRs
        run: |
          echo "Locked issues: $(echo '${{ steps.lock.outputs.locked-issues }}' | jq)"
          echo "Locked PRs: $(echo '${{ steps.lock.outputs.locked-prs }}' | jq)"
