name: pre-commit

on:
  pull_request:
  push:
    branches: ['main', 'release/*']

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    # Install Dependencies for Python
    - name: Install Dependencies for Python
      run: |
        python -m pip install --upgrade pip
        pip install "clang-format==13.0.0"
    - uses: pre-commit/action@v3.0.1
